---
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: web-server
    default_container_image: nginx
    default_container_command: sleep 1d
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Update repo cache
      yum:
        name: '*'
        state: latest

    - name: Install dependencies
      yum:
        name:
          - docker

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy app assets
      copy:
        src: app
        dest: .

    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: ./app
        name: mysuperwebappimage
        source: build

    - name: Run the Docker container
      docker_container:
        name: MySuperWebApp
        image: mysuperwebappimage
        state: started
        ports:
          - 80:80
