name: 'Deploy to AWS'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Build infra'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.4
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-check'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        # TF_VAR_ssh_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}


    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.4
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-input=false'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        TF_VAR_ssh_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.4
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var-file="./env/prod.tfvars"'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        TF_VAR_ssh_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.4
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var-file="./env/prod.tfvars" -auto-approve -input=false'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        TF_VAR_ssh_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}

  setup:
    name: 'Setup environment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run playbook
      run: |
        ansible-playbook -b --inventory hosts.yml --private-key "${{secrets.AWS_PUBLIC_SSH_KEY}}" setup-environment.yml