name: 'Terraform'

on:
  push:
    branches: [ "destroy/**" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Destroy infra'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.4
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init -var-file="./env/prod.tfvars"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        TF_VAR_ssh_public_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}

    - name: Terraform Destroy
      run: terraform plandestroy -var-file="./env/prod.tfvars -auto-approve"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'