name: 'Terraform'

on:
  push:
    branches: [ "destroy" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # - name: Terraform Init
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 1.7.4
    #     tf_actions_subcommand: 'init'
    #     tf_actions_working_dir: '.'
    #     tf_actions_comment: true
    #     args: '-var-file="./env/prod.tfvars"'
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    #     AWS_DEFAULT_REGION: 'us-east-1'
    #     TF_VAR_ssh_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}

    - name: Terraform Destroy
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.4
        tf_actions_subcommand: 'destroy'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        args: '-var-file="./env/prod.tfvars" -auto-approve -input=false'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        TF_VAR_ssh_key: ${{ secrets.AWS_PUBLIC_SSH_KEY }}